[package]
name = "fruitboard-desktop"
version = "0.1.0"
description = "Fruitboard desktop application host"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "fruitboard_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
fruitboard-storage.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
uuid.workspace = true
